version: "3.8"

# networks:
#   laravel:
#     driver: bridge

services:
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: base_php
    restart: unless-stopped
    working_dir: /var/www/data
    volumes:
      - ./src:/var/www/data
    # networks:
    #   - laravel

  mysql:
    # env_file:
    #   - ./src/.env
    image: mysql:8.0-debian
    container_name: base_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: base_laravel
      MYSQL_USER: quangnm
      MYSQL_PASSWORD: quangnm
      MYSQL_ROOT_PASSWORD: root
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
      # TZ: "Asia/Ho_Chi_Minh"
    tty: true
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 10s
    #   retries: 10
    # networks:
    #   - laravel

  nginx:
    image: nginx:1.25.1-alpine
    container_name: base_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/data
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
      - mysql
    # networks:
    #   - laravel
  

 

  
